/**
 * TypeScript definitions for Institusi domain in Dashboard Unit Swasta PPD Gua Musang.
 */

export type InstitusiKategori = "tadika swasta" | "sekolah swasta" | "pusat tuisyen";
export type InstitusiStatus = "aktif" | "tidak aktif" | "digantung";

export interface PortalAccess {
  enabled: boolean;
  credentialStatus: "aktif" | "belum-diset" | "disekat";
  passwordHash: string;
  passwordSalt: string;
  passwordUpdatedAt?: string;
  passwordUpdatedBy?: string;
  passwordAutoGenerated?: boolean;
  loginReady?: boolean;
  fallbackPassword?: string;
  
  // Firebase Auth Production Parameters
  authProvider?: "firebase-auth";
  authUid?: string;
  loginIdentifier?: string;
  authStatus?: "aktif" | "disekat" | "belum-diset";
  activatedBy?: string;
  activatedAt?: string;
  migrationVersion?: number;
  lastPasswordResetAt?: string;
  migrationState?: "legacy" | "hybrid" | "firebase-auth-only";
  legacyFallbackAllowed?: boolean;
}

export interface InstitusiRecord {
  id: string;
  namaInstitusi: string;
  kategori: InstitusiKategori;
  zon: string;
  mukim: string;
  statusOperasi: InstitusiStatus;
  tarikhDaftar: string;
  noRujukan: string;
  alamat: string;
  pengelola?: string;
  telefon?: string;
  yuran_semasa?: number;
  yuranSemasa?: number;
  nama_gb?: string;
  namaGB?: string;
  nama_pengetua?: string;
  namaPengetua?: string;
  alamat_premis?: string;
  bil_murid?: number;
  bilGuru?: number;
  bil_guru?: number;
  tahun_dikemaskini?: string;
  portalAccess?: PortalAccess;
  statusProfil?: "belum-mula" | "sedang-dikemaskini" | "lengkap";
  statusPendaftaran?: "didaftarkan-awal" | "sebahagian" | "lengkap";
  completionPercentage?: number;
  source?: string;
}
